language: python
python:
  - '2.7'
  - '3.5'
install:
  - python setup.py install
  - pip install flake8
before_script: flake8 retry.py
script: python setup.py test
deploy:
  provider: pypi
  user: seemethere
  password:
    secure: QuTo+WxUEte53UxBcUUz1lIXssWIb2P4hAx4agGLFm+k7wRqSq9dzCi5QpS9S3XoxIFIjsSdkcNx0rG6Cz63ztQl9tEhZJKjD2ZkMQsBU8FdjF67E0jp3FhLAB8bhc3TGVLgitkDBFoS85w7wuEnkGmqE6mp/OFhDcpx7Mp8PIDp9o5q8cWR4ah8YkKrj6rofcVCRhDBfARxlFZMZtf+U+Nhn3ZQQCK6MOQHsJFL1+gwmIyvjmHTNiuhYFyIlTAvGXDP6mpp4tBAY+ZA3m+3QfopMmdxtWj1duWwxO3oD/fmb2MHXtnmjudnlKDh9kAuBLpztGpmjcuNoZsYHhvkOfwr+KJD6YiGKlMX+l/+f7Pla364S47MCx6m1erIvv8EMSND6IiZxJwDbyqwNvmLmUJUm538L9VPCYF5kugvR7F2j3c6Ze7Plgxe5djqJyqjlMLgNje73pXwZyxT9OhRT9YYP2B9Lm9a/LLWFuRAXHxLpXMZRYjI6aXG1JmQpNSAe1x6lDiHx5H1Bmdq3HOnzUmw9GcBrdwDyQaYire31WaxmhWZV0K/jokLW5oh9JEsngQNRePIi9azcAo4Ptf1KFMYJyWk6b70i5VfaK7jXgsZ1EmSQvbkfg5H39eVce7p94ULeAbqgwsqnDdD3hHH9A0vmwWZfMKbtaW2tqdFujQ=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: seemethere/retry.it
