language: python
python:
  - '2.7'
  - '3.5'
install:
  - python setup.py install
  - pip install flake8
before_script: flake8 retry.py
script: python setup.py test
deploy:
  provider: pypi
  user: seemethere
  password:
    secure: CBJpuLcwyzvp7+EZ1bKWDor7OVGmmDlrh1V8iAZOK4C5CH4S11a6FglGbofLxbu+TZgzBTRY8+QOUxkMotrw1FnuOKBYlEvLB/HLdFNk4WDQwr+liy4YxyFl0kK9AxQ+w36w6INAdNyeTY/y11YGvSh9HjDqwZY7vhBIZoh6iI9DFiKQ3nxAp0QSggpAnb8HiIg4kSdubzqgwUi/KOnciTf0D3ZRXmUqL9VHONuhxDBjJjUGZe+PnAcBnBTdUrw+T1gZh052y8qQDlaliSNyXnHjIhWUosX9/Mng+8YH3a0DkS+DXBQaPP/WzKggcXVP9llLe+4jBWMpH/UL8Ly0gqNz40rhhunHN3J7EHRIc1rlQb1ToqYdJEX5e+WwUDhl8Afl4POadFwwlGzRH0XYZpXFTADtOS8U+zJi9zS5+eTc1GWNKEMj9sxatAUYHooX0/FVCoDv4DWYzgx1W+187d/ujkAntI67uI9mHc71AZAVdWK3B+7Iunj4sjKe29ivwPYZ1Ssw8xyBTf+dChNCW6Q/lZLoKKPvP3FFwg5g9zN/JWGhI2ThWbbo67535v3viR9o0BEzM2lhU3XUTLrZ8PzwYEjCZjh126hZ/cXBjNZECjhyZ/Wong/92OYBB0Xt7CKLsvbfznbKK8gy5Ml1rMqF9Ed36TGG4lUTbSnOE20=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: seemethere/retry.it
