language: python
python:
- '2.7'
- '3.5'
install:
- python setup.py install
- pip install flake8
before_script: flake8 retry.py
script: python setup.py test
deploy:
  provider: pypi
  user: seemethere
  password:
    secure: gm+8oCNxlRAtn0djYIMTzzgHz0qu0FEV2fQn7ffJjxeBxRjYjQm4c8egBOFZKgG4NOD70dsD6KsvjDkpKWh0wFSYeMYTzcGtnTl7AHYIgwJLSmjaqV//e1hHW9hH2x6UV1flOrGB+V7BJG/1gH9DDgB9YqvHhYQcQXs3svSxppvmcuojp+PoHjiGZ+IanUjPrvAHf6ZhGbcefNwOPfHOeET2eoOZ0kTxSI/SMsdrJy0xGbAQyQxbxYbhIuVUVJmHu6de7/K39DuAEkBaGWWOys+jCMJhqhl0KIeFks0gk3uK5z8+m6PRL+WyLYsMGzLqF6YUjcybsFdOZPcXdmaleP52zG0KrJCzh2y265BUNnqTwSDh3Y9d689dVSP4OwqfruStdc1AhRU9dDRLaceMOWZuEeYf+kyhURQwFWrZApRq0iMBokW73MNFoOYGVDLrHOdWETIpJ+pZHTkhxCT1sapshXm/plxn94WiwnHbEFBfzCk9lEA7VTxukRxkrDrSLF2bAF03PELoMnFUado4YmBgktur7JOTfQXi7uDk8+J7yDVNheyPUpnmdxiWu2WfBPV9FdHIVxkdjzKVs18g6EB6sqobeVr3XSj24WqxW3TGDTUssob1l54sxAql9R4qSAJAmsd46sfSa/wZ/55Biy6RALqrStpqstBB7edkbJw=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: seemethere/retry.it
